name: example3c

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      uses: ./.github/actions/say-hi
      with:
        name: Sergio
        message: How are you?
